config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root "pages#home"

  get "profilo", to: "pages#profilo"

  get "contatti", to: "pages#contatti"

  resources :categories

  resources :items

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :category_items
  has_many :items, through: :category_items

  validates :name, presence: true
end

app/models/category_item.rb
class CategoryItem < ApplicationRecord
  belongs_to :item
  belongs_to :category
end

app/models/item.rb
class Item < ApplicationRecord

  has_many :category_items
  has_many :categories, through: :category_items

  validates :title, presence:true
  validates :image, presence:true

  mount_uploader :image, ImageUploader
  mount_uploader :image_2, ImageUploader

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :all_categories

  def all_categories
    @categories = Category.all
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.all
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @items = Item.where(is_home: true)
  end

  def profilo
  end

  def contatti
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/categories/index.html.erb
<% @categories.each do |cat| %>
  <%= link_to cat.name, category_path(cat) %>
<% end %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>

<%= render partial: "items/item", collection: @category.items.all %>

app/views/items/_item.html.erb
<%= link_to item_path(item), class: "item" do %>
  <%= image_tag item.image.square %>
  <p><%= item.title %></p>
<% end %>

app/views/items/index.html.erb
<%= render partial: "item", collection: @items %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <header>
  	<h1>
      <%= link_to root_path do %>
        <%= image_tag('marinacaldari-logo.png') %>
      <% end %>
    </h1>
    <nav class="extended">
    	<%= link_to "Profilo", profilo_path %>
      <% all_categories.each do |category| %>
        <%= link_to category.name, category_path(category) %>
      <% end %>
      <%= link_to "Contatti", contatti_path %>
    </nav>
    <nav class="menu-toggle">
    	<a href="#">
        <img src="menu.svg">
      </a>
    </nav>
    <div class="menu">
      <nav>
        <%= link_to "Profilo", profilo_path %>
        <% all_categories.each do |category| %>
          <%= link_to category.name, category_path(category) %>
        <% end %>
        <%= link_to "Contatti", contatti_path %>
      </nav>
  	</div>
  </header>

    <%= yield %>
  </body>
</html>

app/views/pages/contatti.html.erb
<h1>This is contatti</h1>

app/views/pages/home.html.erb
<h1>This is the home page</h1>

<% @items.each do |item| %>
    <% if item.image_2.present? %>
      <%= image_tag item.image_2.square %>
    <% else %>
      <%= image_tag item.image.square %>
    <% end %>
<% end %>

app/views/pages/profilo.html.erb
<h1>This is profilo</h1>